---
- hosts: all
  become: true
  become_user: root
  vars:
    hostname: "{{ ansible_facts['hostname'] }}"
    address: "{{ ansible_mgm.ipv4.address }}"
    os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  tasks:

  - name: Drupal
    shell: docker exec -it docker_ikp_cms_1 /var/www/html/vendor/bin/drush status|head -n1|cut -d ' ' -f6
    register: drupal
    ignore_errors: yes
    tags: drupal

  - set_fact:
      drupal_out: "{% if (drupal.stdout == '') %}{%else%}Drupal: {{ drupal.stdout }}{% endif %}"

  - name: stworzenie pliku
    copy:
      dest: /home/itsadm1/ansible/insight/results/drupal_ansible.csv
      content: "hostname,ip_mgm,os,version"
    delegate_to: localhost

  - name: zrzut do pliku
    lineinfile:
      dest: /home/itsadm1/ansible/insight/tools/drupal_ansible.csv
      line: "{{ hostname }},{{ address }},{{ os }},{{ drupal_out }}"
      create: yes
      owner: itsadm1
      group: itsadm1
      insertafter: EOF
    delegate_to: localhost