---
- hosts: all
  become: true
  become_user: root
  vars:
    hostname: "{{ ansible_facts['hostname'] }}"
    address: "{{ ansible_mgm.ipv4.address }}"
    os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  tasks:

  - name: Elasticsearch
    shell: yum info elasticsearch|grep "Version"|awk '{print $3}'
    register: elastic
    ignore_errors: yes
    tags: elastic

  - set_fact:
      elastic_out: "{% if (elastic.stdout == '') %}{%else%}Elasticsearch: {{ elastic.stdout }}{% endif %}"

  - name: stworzenie pliku
    copy:
      dest: /home/itsadm1/ansible/insight/tools/elastic_ansible.csv
      content: "hostname,ip_mgm,os,version"
    delegate_to: localhost

  - name: zrzut do pliku
    lineinfile:
      dest: /home/itsadm1/ansible/insight/tools/elastic_ansible.csv
      line: "{{ hostname }},{{ address }},{{ os }},{{ elastic_out }}"
      create: yes
      owner: itsadm1
      group: itsadm1
      insertafter: EOF
    delegate_to: localhost