---
- hosts: all
  become: true
  become_user: root
  vars:
    hostname: "{{ ansible_facts['hostname'] }}"
    address: "{{ ansible_mgm.ipv4.address }}"
    os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  tasks:

  - name: filebeat
    shell: filebeat version|awk '{print $3}'
    register: filebeat
    ignore_errors: yes
    tags: filebeat

  - set_fact:
      filebeat_out: "{% if (filebeat.stdout == '') %}{%else%}Filebeat: {{ filebeat.stdout }}{% endif %}"

  - name: stworzenie pliku
    copy:
      dest: /home/itsadm1/ansible/insight/tools/filebeat_ansible.csv
      content: "hostname,ip_mgm,os,version"
    delegate_to: localhost

  - name: zrzut do pliku
    lineinfile:
      dest: /home/itsadm1/ansible/insight/tools/filebeat_ansible.csv
      line: "{{ hostname }},{{ address }},{{ os }},{{ filebeat_out }}"
      create: yes
      owner: itsadm1
      group: itsadm1
      insertafter: EOF
    delegate_to: localhost