---
- hosts: all
  become: true
  become_user: root
  vars:
    hostname: "{{ ansible_facts['hostname'] }}"
    address: "{{ ansible_mgm.ipv4.address }}"
    os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  tasks:

  - name: GlusterFS
    shell: yum info glusterfs|grep "Version"|awk '{print $3}'
    register: gluster
    ignore_errors: yes
    tags: gluster

  - set_fact:
      gluster_out: "{% if (gluster.stdout == '') %}{%else%}GlusterFS: {{ gluster.stdout }}{% endif %}"

  - name: stworzenie pliku
    copy:
      dest: /home/itsadm1/ansible/insight/tools/gluster_ansible.csv
      content: "hostname,ip_mgm,os,version"
    delegate_to: localhost

  - name: zrzut do pliku
    lineinfile:
      dest: /home/itsadm1/ansible/insight/tools/gluster_ansible.csv
      line: "{{ hostname }},{{ address }},{{ os }},{{ gluster_out }}"
      create: yes
      owner: itsadm1
      group: itsadm1
      insertafter: EOF
    delegate_to: localhost