---
- hosts: all
  become: true
  become_user: root
  vars:
    hostname: "{{ ansible_facts['hostname'] }}"
    address: "{{ ansible_mgm.ipv4.address }}"
    os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  tasks:

  - name: Kibana
    shell: yum info kibana|grep "Version"|awk '{print $3}'
    register: kibana
    ignore_errors: yes
    tags: kibana

  - set_fact:
      kibana_out: "{% if (kibana.stdout == '') %}{%else%}Kibana: {{ kibana.stdout }}{% endif %}"

  - name: stworzenie pliku
    copy:
      dest: /home/itsadm1/ansible/insight/tools/kibana_ansible.csv
      content: "hostname,ip_mgm,os,version"
    delegate_to: localhost

  - name: zrzut do pliku
    lineinfile:
      dest: /home/itsadm1/ansible/insight/tools/kibana_ansible.csv
      line: "{{ hostname }},{{ address }},{{ os }},{{ elastic_out }}"
      create: yes
      owner: itsadm1
      group: itsadm1
      insertafter: EOF
    delegate_to: localhost