---
- hosts: all
  become: true
  become_user: root
  vars:
    hostname: "{{ ansible_facts['hostname'] }}"
    address: "{{ ansible_mgm.ipv4.address }}"
    os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  tasks:

  - name: MongoDB
    shell:  mongo --version|grep "version"|head -1|awk '{print $4}'
    register: mongo
    ignore_errors: yes
    tags: mongo

  - name: MongoDB check
    shell: "{% if (mongo.stdout == 'MongoDB') %} mongo --version|grep 'version'|head -1|awk '{print $7}' {% else %}  mongo --version|grep 'version'|head -1|awk '{print $4}' {% endif %}"
    register: mongo
    ignore_errors: yes

  - set_fact:
      mongo_out: "{% if (mongo.stdout == '') %}{%else%}Mongo: {{ mongo.stdout }}{% endif %}"

  - name: stworzenie pliku
    copy:
      dest: /home/itsadm1/ansible/insight/results/mongo_ansible.csv
      content: "hostname;ip_mgm;os;version"
    delegate_to: localhost

  - name: zrzut do pliku
    lineinfile:
      dest: /home/itsadm1/ansible/insight/results/mongo_ansible.csv
      line: "{{ hostname }};{{ address }};{{ os }};{{ mongo_out }}"
      create: yes
      owner: itsadm1
      group: itsadm1
      insertafter: EOF
    delegate_to: localhost
