---
- hosts: all
  become: true
  become_user: root
  vars:
    hostname: "{{ ansible_facts['hostname'] }}"
    address: "{{ ansible_mgm.ipv4.address }}"
    os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  tasks:

  - name: PostgreSQL
    shell: psql -V|awk '{print $3}'
    register: psql
    ignore_errors: yes
    tags: psql

  - set_fact:
      psql_out: "{% if (psql.stdout == '') %}{%else%}PostgreSQL: {{ psql.stdout }}{% endif %}"

  - name: stworzenie pliku
    copy:
      dest: /home/itsadm1/ansible/insight/tools/psql_ansible.csv
      content: "hostname,ip_mgm,os,version"
    delegate_to: localhost

  - name: zrzut do pliku
    lineinfile:
      dest: /home/itsadm1/ansible/insight/tools/psql_ansible.csv
      line: "{{ hostname }},{{ address }},{{ os }},{{ psql_out }}"
      create: yes
      owner: itsadm1
      group: itsadm1
      insertafter: EOF
    delegate_to: localhost