---
- hosts: all
  become: true
  become_user: root
  vars:
    hostname: "{{ ansible_facts['hostname'] }}"
    address: "{{ ansible_mgm.ipv4.address }}"
    os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  tasks:

  - name: wildfly
    shell: readlink -f /opt/wildfly|cut -d'-' -f2
    register: wildfly
    ignore_errors: yes

  - name: wildfly check
    shell: "{% if (wildfly.stdout == '/opt/ejbca') %} echo '' {%else%} readlink -f /opt/wildfly|cut -d'-' -f2 {% endif %}"
    register: wildfly
    ignore_errors: yes

  - set_fact:
      wildfly_out: "{% if (wildfly.stdout == '') %}{%else%}WildFLy: {{ wildfly.stdout }}{% endif %}"

  - name: stworzenie pliku
    copy:
      dest: /home/itsadm1/ansible/insight/results/wildfly_ansible.csv
      content: "hostname;ip_mgm;os;version"
    delegate_to: localhost

  - name: zrzut do pliku
    lineinfile:
      dest: /home/itsadm1/ansible/insight/results/wildfly_ansible.csv
      line: "{{ hostname }};{{ address }};{{ os }};{{ wildfly_out }}"
      create: yes
      owner: itsadm1
      group: itsadm1
      insertafter: EOF
    delegate_to: localhost
