---
- hosts: all
  become: true
  become_user: root
  vars:
    hostname: "{{ ansible_facts['hostname'] }}"
    address: "{{ ansible_mgm.ipv4.address }}"
    os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  tasks:

  - name: Zabbix
    shell: yum info zabbix-agent|grep "Version"|awk '{print $3}'
    register: zabbix
    ignore_errors: yes

  - set_fact:
      zabbix_out: "{% if (zabbix.stdout == '') %}{%else%}Zabbix: {{ zabbix.stdout }}{% endif %}"
      
  - name: stworzenie pliku
    copy:
      dest: /home/itsadm1/ansible/insight/tools/zabbix_ansible.csv
      content: "hostname,ip_mgm,os,version"
    delegate_to: localhost

  - name: zrzut do pliku
    lineinfile:
      dest: /home/itsadm1/ansible/insight/tools/zabbix_ansible.csv
      line: "{{ hostname }},{{ address }},{{ os }},{{ zabbix_out }}"
      create: yes
      owner: itsadm1
      group: itsadm1
      insertafter: EOF
    delegate_to: localhost